import { useEffect, useMemo, useRef, useState } from 'react';
import { AlertTriangle, ArrowRight, Check, ChevronRight, CircleX, ClipboardList, RotateCcw, Ship, X } from 'lucide-react';
import source from './data/generated/workbook.json';
import { active, daysBetween, demoToday, formatDate, formatMoney, groupBy, label, maxRisk, primaryException, rebaseDate, severityName, severityRank, type Row } from './domain/calculations';

type Filters = { vendor: string; velocity: string; channel: string; exceptionType: string };
type Drill = { type: 'milestone' | 'issue' | 'vendor' | 'shipment' | 'line' | 'kpi'; id: 'at-risk' | 'revenue-risk' | 'eta-later' | 'stale' | string } | null;
type Lens = 'vendors' | 'inbound';
const all = 'ALL';
const raw = source as unknown as Record<string, Row[]>;
const sheets = (name: string) => raw[name] || [];
const today = demoToday();
const initialFilters: Filters = { vendor: all, velocity: all, channel: all, exceptionType: all };
const get = (row: Row | undefined, key: string) => String(row?.[key] ?? '—');
const numeric = (row: Row | undefined, key: string) => Number(row?.[key] ?? 0);
const statusClass = (severity: unknown) => severity === 'SEV-HIGH' ? 'high' : severity === 'SEV-MEDIUM' ? 'medium' : 'low';
const displayIssue = (value: unknown) => value === 'EXT-NONE' ? 'Unclassified Issue' : label(value);

function Severity({ id }: { id: unknown }) { return <span className={`severity ${statusClass(id)}`}>{severityName(id)}</span>; }
function Metric({ title, value, tip, illustrative, onClick }: { title: string; value: string | number; tip: string; illustrative?: boolean; onClick: () => void }) {
  return <button className="metric" title={`${tip} Click to drill into relevant PO lines.`} onClick={onClick}><span>{title}</span><strong>{value}</strong>{illustrative && <small>Illustrative</small>}<i>View PO lines <ChevronRight size={13} /></i></button>;
}
function Bar({ name, count, severity, onClick, detail }: { name: string; count: number; severity: unknown; onClick: () => void; detail?: string }) {
  return <button className="bar-row" onClick={onClick} aria-label={`Drill into ${name}`}><span className={`bar-fill ${statusClass(severity)}`} style={{ width: `${Math.max(12, count)}%` }} /><span className="bar-label">{name}{detail && <small>{detail}</small>}</span><b>{count}</b><ChevronRight size={15} /></button>;
}

export default function App() {
  const [filters, setFilters] = useState<Filters>(initialFilters);
  const [lens, setLens] = useState<Lens>('vendors');
  const [drill, setDrill] = useState<Drill>(null);
  const [selectedLine, setSelectedLine] = useState<string | null>(null);
  const [selectedException, setSelectedException] = useState<string | null>(null);
  const [chosenOptions, setChosenOptions] = useState<Record<string, string>>({});
  const [approved, setApproved] = useState<Record<string, boolean>>({});
  const workspaceRef = useRef<HTMLElement>(null);
  const headingRef = useRef<HTMLHeadingElement>(null);

  const model = useMemo(() => {
    const vendors = sheets('Vendors'), products = sheets('Products'), pos = sheets('Purchase Orders'), lines = sheets('PO Lines');
    const exceptions = sheets('Exceptions'), milestones = [...sheets('Milestone Definitions')].sort((a, b) => numeric(a, 'StepNumber') - numeric(b, 'StepNumber'));
    const index = (rows: Row[], key: string) => new Map(rows.map(row => [get(row, key), row]));
    return { vendors, products, pos, lines, exceptions, milestones, owners: index(sheets('Owners'), 'OwnerID'), productById: index(products, 'ProductID'), poById: index(pos, 'PurchaseOrderID'), vendorById: index(vendors, 'VendorID'), typeById: index(sheets('Exception Types'), 'ExceptionTypeID'), milestoneById: index(milestones, 'MilestoneID'), referenceById: index(sheets('Reference Values'), 'ReferenceValueID'), shipmentById: index(sheets('Inbound Shipments'), 'InboundShipmentID'), decisionByException: index(sheets('Decisions'), 'ExceptionID'), alternatives: sheets('Decision Alternatives'), strategyById: index(sheets('Response Strategies'), 'ResponseStrategyID'), capacity: sheets('DC Capacity') };
  }, []);
  const refName = (id: unknown) => get(model.referenceById.get(String(id)), 'DisplayValue') !== '—' ? get(model.referenceById.get(String(id)), 'DisplayValue') : label(id);
  const ownerName = (id: unknown) => get(model.owners.get(String(id)), 'OwnerName') !== '—' ? get(model.owners.get(String(id)), 'OwnerName') : 'Unassigned';
  const vendorOf = (line: Row) => model.vendorById.get(get(model.poById.get(get(line, 'PurchaseOrderID')), 'VendorID'));
  const lineMatchesBase = (line: Row) => {
    const vendor = get(vendorOf(line), 'VendorID');
    return (filters.vendor === all || vendor === filters.vendor) && (filters.velocity === all || get(line, 'VelocityID') === filters.velocity) && (filters.channel === all || get(line, 'ChannelID') === filters.channel);
  };
  const activeExceptions = useMemo(() => model.exceptions.filter(active).filter(exception => {
    const line = model.lines.find(x => get(x, 'POLineID') === get(exception, 'POLineID'));
    return !!line && lineMatchesBase(line) && (filters.exceptionType === all || get(exception, 'ExceptionTypeID') === filters.exceptionType);
  }), [model, filters]);
  const allFilteredLines = useMemo(() => model.lines.filter(lineMatchesBase).filter(line => filters.exceptionType === all || activeExceptions.some(ex => get(ex, 'POLineID') === get(line, 'POLineID'))), [model, filters, activeExceptions]);
  const activeByLine = useMemo(() => groupBy(activeExceptions, 'POLineID'), [activeExceptions]);
  const affectedLines = useMemo(() => model.lines.filter(line => activeByLine[get(line, 'POLineID')]), [model, activeByLine]);
  const issueGroups = useMemo(() => Object.entries(groupBy(activeExceptions, 'ExceptionTypeID')).map(([id, ex]) => ({ id, ex, count: new Set(ex.map(x => get(x, 'POLineID'))).size, severity: ex.reduce<string>((max, x) => severityRank(x.SeverityID) > severityRank(max) ? String(x.SeverityID) : max, 'SEV-LOW'), risk: Object.values(groupBy(ex, 'POLineID')).reduce((sum, group) => sum + maxRisk(group), 0) })).sort((a, b) => b.count - a.count || b.risk - a.risk || severityRank(b.severity) - severityRank(a.severity)).slice(0, 6), [activeExceptions]);
  const riskByLine = Object.values(activeByLine).reduce((sum, ex) => sum + maxRisk(ex), 0);
  const atRiskPOs = new Set(affectedLines.map(line => get(line, 'PurchaseOrderID'))).size;
  const etaLaterLines = allFilteredLines.filter(line => get(line, 'CurrentMilestoneID') !== 'MS-13' && numeric(line, 'CurrentETA') - numeric(line, 'PlannedETA') > 0);
  const staleLines = allFilteredLines.filter(line => get(line, 'CurrentMilestoneID') !== 'MS-13' && (daysBetween(rebaseDate(line.LastUpdateDate, today), today) ?? 0) > numeric(model.milestoneById.get(get(line, 'CurrentMilestoneID')), 'StaleUpdateThresholdDays'));
  const etaLater = new Set(etaLaterLines.map(line => get(line, 'POLineID'))).size;
  const stale = new Set(staleLines.map(line => get(line, 'POLineID'))).size;
  const milestoneCounts = useMemo(() => Object.fromEntries(model.milestones.map(m => {
    const current = affectedLines.filter(line => get(line, 'CurrentMilestoneID') === get(m, 'MilestoneID'));
    const severity = current.flatMap(line => activeByLine[get(line, 'POLineID')] || []).reduce<string>((max, ex) => severityRank(ex.SeverityID) > severityRank(max) ? String(ex.SeverityID) : max, 'SEV-LOW');
    return [get(m, 'MilestoneID'), { count: current.length, severity }];
  })), [model, affectedLines, activeByLine]);
  const lineExceptions = (id: string) => activeByLine[id] || [];
  const rankedLines = (lines: Row[]) => [...lines].sort((a, b) => { const ea = primaryException(lineExceptions(get(a, 'POLineID'))), eb = primaryException(lineExceptions(get(b, 'POLineID'))); return numeric(eb, 'BusinessImpactScore') - numeric(ea, 'BusinessImpactScore') || severityRank(eb?.SeverityID) - severityRank(ea?.SeverityID) || numeric(eb, 'RevenueAtRisk') - numeric(ea, 'RevenueAtRisk'); });
  const preview = rankedLines(affectedLines).slice(0, 4);
  const vendorRisks = useMemo(() => Object.entries(groupBy(affectedLines, 'PurchaseOrderID')).flatMap(([, lines]) => lines).reduce<Record<string, Row[]>>((map, line) => { const id = get(vendorOf(line), 'VendorID'); (map[id] ||= []).push(line); return map; }, {}), [affectedLines]);
  const topVendors = Object.entries(vendorRisks).map(([id, lines]) => ({ id, lines, count: lines.length, impact: lines.reduce((sum, line) => sum + numeric(primaryException(lineExceptions(get(line, 'POLineID'))), 'BusinessImpactScore'), 0), risk: lines.reduce((sum, line) => sum + maxRisk(lineExceptions(get(line, 'POLineID'))), 0), severity: lines.flatMap(line => lineExceptions(get(line, 'POLineID'))).reduce<string>((max, ex) => severityRank(ex.SeverityID) > severityRank(max) ? String(ex.SeverityID) : max, 'SEV-LOW') })).sort((a, b) => b.count - a.count || b.impact - a.impact || b.risk - a.risk).slice(0, 5);
  const topShipments = useMemo(() => Object.entries(groupBy(affectedLines.filter(line => model.shipmentById.has(get(line, 'InboundShipmentID'))), 'InboundShipmentID')).map(([id, lines]) => ({ id, lines, shipment: model.shipmentById.get(id), count: lines.length, priority: lines.filter(line => ['VEL-A', 'VEL-B'].includes(get(line, 'VelocityID'))).reduce((sum, x) => sum + numeric(x, 'Quantity'), 0), severity: lines.flatMap(line => lineExceptions(get(line, 'POLineID'))).reduce<string>((max, ex) => severityRank(ex.SeverityID) > severityRank(max) ? String(ex.SeverityID) : max, 'SEV-LOW') })).sort((a, b) => b.count - a.count || b.priority - a.priority).slice(0, 5), [affectedLines, model]);
  const capacityConflicts = model.capacity.filter(row => (rebaseDate(row.CapacityDate, today) ?? '') >= today && numeric(row, 'PlannedInboundUnits') > numeric(row, 'AvailableReceivingCapacityUnits')).length;
  const forumCounts = Object.entries(groupBy(activeExceptions, 'PlanningForumID')).map(([id, ex]) => ({ id, count: ex.length }));

  const contextLines = useMemo(() => {
    if (!drill) return [];
    const base = affectedLines;
    if (drill.type === 'line') return base.filter(line => get(line, 'POLineID') === drill.id);
    if (drill.type === 'milestone') return base.filter(line => get(line, 'CurrentMilestoneID') === drill.id);
    if (drill.type === 'issue') return base.filter(line => lineExceptions(get(line, 'POLineID')).some(ex => get(ex, 'ExceptionTypeID') === drill.id));
    if (drill.type === 'vendor') return base.filter(line => get(vendorOf(line), 'VendorID') === drill.id);
    if (drill.type === 'kpi') return drill.id === 'at-risk' || drill.id === 'revenue-risk' ? affectedLines : drill.id === 'eta-later' ? etaLaterLines : staleLines;
    return base.filter(line => get(line, 'InboundShipmentID') === drill.id);
  }, [drill, affectedLines, etaLaterLines, staleLines]);
  const queue = rankedLines(contextLines);
  const selected = queue.find(line => get(line, 'POLineID') === selectedLine) || queue[0];
  const selectedEx = lineExceptions(get(selected, 'POLineID')).find(ex => get(ex, 'ExceptionID') === selectedException) || primaryException(lineExceptions(get(selected, 'POLineID')));
  const contextTitle = !drill ? '' : drill.type === 'kpi' ? ({ 'at-risk': 'KPI: At-Risk POs', 'revenue-risk': 'KPI: Revenue at Risk', 'eta-later': 'KPI: ETA Later Than Plan', stale: 'KPI: Stale Updates' }[drill.id] || 'KPI drilldown') : drill.type === 'milestone' ? `Milestone: ${get(model.milestoneById.get(drill.id), 'MilestoneName')}` : drill.type === 'issue' ? `Issue: ${displayIssue(get(model.typeById.get(drill.id), 'ExceptionTypeName') === 'None' ? 'EXT-NONE' : get(model.typeById.get(drill.id), 'ExceptionTypeName'))}` : drill.type === 'vendor' ? `Vendor: ${get(model.vendorById.get(drill.id), 'VendorName')}` : drill.type === 'shipment' ? `Inbound Shipment: ${drill.id}` : `PO Line: ${drill.id}`;

  const open = (next: NonNullable<Drill>, exact?: string) => { setDrill(next); setSelectedLine(exact || null); setSelectedException(null); };
  useEffect(() => { if (!drill) return; const timer = window.setTimeout(() => { workspaceRef.current?.scrollIntoView({ behavior: window.matchMedia('(prefers-reduced-motion: reduce)').matches ? 'auto' : 'smooth', block: 'start' }); headingRef.current?.focus({ preventScroll: true }); }, 20); return () => window.clearTimeout(timer); }, [drill]);
  const reset = () => { setFilters(initialFilters); setLens('vendors'); setDrill(null); setSelectedLine(null); setSelectedException(null); setChosenOptions({}); setApproved({}); window.scrollTo({ top: 0, behavior: 'smooth' }); };

  const selectOptions = (domain: string) => sheets('Reference Values').filter(row => get(row, 'Domain') === domain);
  const optionId = (row: Row) => String(row.ReferenceValueID ?? row.VendorID ?? row.ExceptionTypeID ?? '');
  const field = (key: keyof Filters, text: string, options: Row[]) => <label className="filter"><span>{text}</span><select value={filters[key]} onChange={e => setFilters({ ...filters, [key]: e.target.value })}><option value={all}>All</option>{options.map(x => <option key={optionId(x)} value={optionId(x)}>{get(x, 'DisplayValue') !== '—' ? get(x, 'DisplayValue') : get(x, 'VendorName') !== '—' ? get(x, 'VendorName') : displayIssue(get(x, 'ExceptionTypeID'))}</option>)}</select></label>;

  return <><header className="app-header"><div><h1>Supply Chain Control Tower</h1></div><div className="header-actions"><span className="mock">Mock Data</span><span className="asof">As of {formatDate(today)}</span><button className="reset" onClick={reset}><RotateCcw size={15} /> Reset Demo</button></div></header>
    <main className="page">
      <section className="metrics" aria-label="Key performance indicators">
        <Metric title="At-Risk POs" value={atRiskPOs} tip="Distinct purchase orders with at least one active exception." onClick={() => open({ type: 'kpi', id: 'at-risk' })} />
        <Metric title="Revenue at Risk" value={formatMoney(riskByLine, true)} tip={`Illustrative sample exposure: ${formatMoney(riskByLine)}. Maximum active exception exposure per PO line.`} illustrative onClick={() => open({ type: 'kpi', id: 'revenue-risk' })} />
        <Metric title="ETA Later Than Plan" value={etaLater} tip="Distinct in-flow PO lines whose current ETA is later than planned ETA." onClick={() => open({ type: 'kpi', id: 'eta-later' })} />
        <Metric title="Stale Updates" value={stale} tip="Distinct in-flow PO lines whose rebased last update exceeds the milestone stale threshold." onClick={() => open({ type: 'kpi', id: 'stale' })} />
      </section>
      <section className="filters" aria-label="Global filters">{field('vendor', 'Vendor', model.vendors)}{field('velocity', 'Velocity', selectOptions('Velocity'))}{field('channel', 'Channel', selectOptions('Channel'))}{field('exceptionType', 'Exception Type', model.typeById ? sheets('Exception Types') : [])}<button className="clear" onClick={() => setFilters(initialFilters)}>Clear Filters</button></section>
      <section className="rail-section"><div className="section-heading"><h2>13-Step Milestone Overview</h2><span>{affectedLines.length} active PO lines</span></div><div className="rail">{model.milestones.map((m, index) => { const info = milestoneCounts[get(m, 'MilestoneID')]; const chosen = drill?.type === 'milestone' && drill.id === get(m, 'MilestoneID'); return <button key={get(m, 'MilestoneID')} className={`milestone ${statusClass(info.severity)} ${chosen ? 'selected' : ''}`} title={`${get(m, 'StageGroup')} • target ${numeric(m, 'TargetDays')} days • stale after ${numeric(m, 'StaleUpdateThresholdDays')} days • ${info.count} affected PO lines`} onClick={() => open({ type: 'milestone', id: get(m, 'MilestoneID') })}><span className="step">{index + 1}</span><span className="milestone-name">{get(m, 'MilestoneName')}</span><b>{info.count}</b><small>{get(m, 'StageGroup')}</small></button>; })}</div></section>
      <section className="panels">
        <article className="panel"><div className="panel-title"><h2>Issues</h2><span>Active PO lines</span></div><div className="bars">{issueGroups.length ? issueGroups.map(item => <Bar key={item.id} name={displayIssue(get(model.typeById.get(item.id), 'ExceptionTypeName') === 'None' ? 'EXT-NONE' : get(model.typeById.get(item.id), 'ExceptionTypeName'))} count={item.count} severity={item.severity} onClick={() => open({ type: 'issue', id: item.id })} />) : <p className="empty">No active issues after filtering.</p>}</div></article>
        <article className="panel"><div className="panel-title"><h2>S&amp;OE Exception Workbench Preview</h2><span>Priority queue</span></div><div className="preview-table">{preview.length ? preview.map(line => { const ex = primaryException(lineExceptions(get(line, 'POLineID'))); const more = lineExceptions(get(line, 'POLineID')).length - 1; return <button className="preview-row" key={get(line, 'POLineID')} onClick={() => open({ type: 'line', id: get(line, 'POLineID') }, get(line, 'POLineID'))}><span><Severity id={ex?.SeverityID} /> {displayIssue(get(model.typeById.get(get(ex, 'ExceptionTypeID')), 'ExceptionTypeName') === 'None' ? 'EXT-NONE' : get(model.typeById.get(get(ex, 'ExceptionTypeID')), 'ExceptionTypeName'))}{more > 0 && <em>+{more}</em>}</span><span>{ownerName(ex?.OwnerID)}</span><span className="action-link">{get(ex, 'RecommendedAction')} <ArrowRight size={13} /></span><b>{formatMoney(maxRisk(lineExceptions(get(line, 'POLineID'))), true)}</b></button>; }) : <p className="empty">No priority PO lines after filtering.</p>}</div></article>
        <article className="panel"><div className="panel-title"><h2>Vendor &amp; Inbound Risk Lens</h2><div className="segmented"><button onClick={() => setLens('vendors')} className={lens === 'vendors' ? 'active' : ''}>Vendors</button><button onClick={() => setLens('inbound')} className={lens === 'inbound' ? 'active' : ''}>Inbound</button></div></div><div className="bars">{lens === 'vendors' ? topVendors.map(item => <Bar key={item.id} name={get(model.vendorById.get(item.id), 'VendorName')} count={item.count} severity={item.severity} onClick={() => open({ type: 'vendor', id: item.id })} />) : <>{topShipments.map(item => <Bar key={item.id} name={item.id} detail={`${refName(item.shipment?.ModeID)} · ${get(model.vendorById.get(get(item.shipment, 'VendorID')), 'VendorName')}`} count={item.count} severity={item.severity} onClick={() => open({ type: 'shipment', id: item.id })} />)}<p className="capacity"><AlertTriangle size={15} /> {capacityConflicts} upcoming DC capacity conflicts</p></>} {!topVendors.length && lens === 'vendors' && <p className="empty">No vendor risk after filtering.</p>}</div><div className="forum"><span>Planning Forum Lens</span>{forumCounts.map(item => <b key={item.id}>{refName(item.id)} <i>{item.count}</i></b>)}</div></article>
      </section>
      {drill && <section ref={workspaceRef} className="workspace" aria-live="polite"><div className="workspace-head"><div><span className="eyebrow">Drilldown Workspace</span><h2 ref={headingRef} tabIndex={-1}>{contextTitle}</h2><p>{queue.length} resulting PO line{queue.length === 1 ? '' : 's'}</p></div><button className="close" onClick={() => { setDrill(null); setSelectedLine(null); }}><X size={17} /> Close</button></div><div className="workspace-grid"><div className="queue"><div className="queue-label">PO-line queue <span>One row per PO line</span></div>{queue.length ? queue.map(line => { const ex = primaryException(lineExceptions(get(line, 'POLineID'))); const more = lineExceptions(get(line, 'POLineID')).length - 1; return <button key={get(line, 'POLineID')} className={`queue-row ${get(selected, 'POLineID') === get(line, 'POLineID') ? 'selected' : ''}`} onClick={() => { setSelectedLine(get(line, 'POLineID')); setSelectedException(null); }}><div>{ex ? <><Severity id={ex.SeverityID} /><b>{numeric(ex, 'BusinessImpactScore')}</b></> : <><span className="no-issue">No issue</span><b>—</b></>}</div><div><strong>{get(line, 'PurchaseOrderID')} / {get(line, 'LineNumber')}</strong><span>{get(model.productById.get(get(line, 'ProductID')), 'SKU')} · {get(vendorOf(line), 'VendorName')}</span></div><div><strong>{ex ? <>{displayIssue(get(model.typeById.get(get(ex, 'ExceptionTypeID')), 'ExceptionTypeName') === 'None' ? 'EXT-NONE' : get(model.typeById.get(get(ex, 'ExceptionTypeID')), 'ExceptionTypeName'))} {more > 0 && <em>+{more}</em>}</> : 'No active exception'}</strong><span>{numeric(line, 'ScheduleVariance') ? `${numeric(line, 'ScheduleVariance') > 0 ? '+' : ''}${numeric(line, 'ScheduleVariance')}d` : '—'} · {formatMoney(maxRisk(lineExceptions(get(line, 'POLineID'))), true)}</span></div></button>; }) : <p className="empty">No PO lines match this context and the current filters.</p>}</div>
        <aside className="detail">{selected ? <><div className="detail-title"><span>Selected PO line</span><strong>{get(selected, 'PurchaseOrderID')} / {get(selected, 'LineNumber')}</strong></div><dl className="facts"><div><dt>SKU / Category</dt><dd>{get(model.productById.get(get(selected, 'ProductID')), 'SKU')} · {get(model.productById.get(get(selected, 'ProductID')), 'Category')}</dd></div><div><dt>Vendor / Origin</dt><dd>{get(vendorOf(selected), 'VendorName')} · {get(vendorOf(selected), 'OriginCountry')}</dd></div><div><dt>Quantity / Channel</dt><dd>{numeric(selected, 'Quantity').toLocaleString()} · {refName(selected.ChannelID)}</dd></div><div><dt>Velocity / Milestone</dt><dd>{refName(selected.VelocityID)} · {get(model.milestoneById.get(get(selected, 'CurrentMilestoneID')), 'MilestoneName')}</dd></div><div><dt>Days at milestone</dt><dd>{numeric(selected, 'DaysAtMilestone')} / target {numeric(model.milestoneById.get(get(selected, 'CurrentMilestoneID')), 'TargetDays')} days</dd></div><div><dt>Plan / Current ETA</dt><dd>{formatDate(rebaseDate(selected.PlannedETA, today))} / {formatDate(rebaseDate(selected.CurrentETA, today))}</dd></div><div><dt>ETA movement / Confidence</dt><dd>{numeric(selected, 'ETAMovementDays') > 0 ? '+' : ''}{numeric(selected, 'ETAMovementDays')}d · {refName(selected.ETAConfidenceID)}</dd></div><div><dt>Last update</dt><dd>{formatDate(rebaseDate(selected.LastUpdateDate, today))} · {get(selected, 'StaleUpdateFlag') === 'Y' ? 'Stale' : 'Current'}</dd></div></dl>{selectedEx ? <><div className="exception-tabs">{lineExceptions(get(selected, 'POLineID')).map(ex => <button className={get(selectedEx, 'ExceptionID') === get(ex, 'ExceptionID') ? 'active' : ''} onClick={() => setSelectedException(get(ex, 'ExceptionID'))} key={get(ex, 'ExceptionID')}><Severity id={ex.SeverityID} /> {displayIssue(get(model.typeById.get(get(ex, 'ExceptionTypeID')), 'ExceptionTypeName') === 'None' ? 'EXT-NONE' : get(model.typeById.get(get(ex, 'ExceptionTypeID')), 'ExceptionTypeName'))}</button>)}</div><div className="exception-detail"><p><b>Impact {numeric(selectedEx, 'BusinessImpactScore')}</b> · {formatMoney(numeric(selectedEx, 'RevenueAtRisk'), true)} illustrative risk</p><p>Owner: {ownerName(selectedEx.OwnerID)} · Due {formatDate(rebaseDate(selectedEx.DueDate, today))} · {refName(selectedEx.ActionStatusID)}</p><p>{get(selectedEx, 'Notes')}</p></div><Decision exception={selectedEx} model={model} choice={chosenOptions[get(selectedEx, 'ExceptionID')]} approved={approved[get(selectedEx, 'ExceptionID')]} onChoose={option => setChosenOptions({ ...chosenOptions, [get(selectedEx, 'ExceptionID')]: option })} onApprove={() => setApproved({ ...approved, [get(selectedEx, 'ExceptionID')]: true })} /></> : <p className="empty">This PO line has no active exception. It is included because it meets the KPI condition.</p>}</> : <p className="empty">No selected PO line.</p>}</aside></div></section>}
    </main></>;
}

function Decision({ exception, model, choice, approved, onChoose, onApprove }: { exception: Row; model: ReturnType<typeof useMemo<any>>; choice?: string; approved?: boolean; onChoose: (id: string) => void; onApprove: () => void }) {
  const decision = model.decisionByException.get(get(exception, 'ExceptionID'));
  const options = decision ? model.alternatives.filter((option: Row) => get(option, 'DecisionID') === get(decision, 'DecisionID')) : [];
  const selected = options.find((option: Row) => get(option, 'DecisionAlternativeID') === choice);
  return <section className="decision"><div className="decision-heading"><ClipboardList size={17} /><h3>Decision options <small>Illustrative</small></h3></div><p className="decision-note">Costs, recovery, service and protection values are sample scenario assumptions.</p>{!options.length ? <p className="empty">Decision options have not yet been defined for this exception.</p> : <>{options.map((option: Row) => <button key={get(option, 'DecisionAlternativeID')} className={`option ${choice === get(option, 'DecisionAlternativeID') ? 'selected' : ''}`} onClick={() => onChoose(get(option, 'DecisionAlternativeID'))}><span><b>{get(model.strategyById.get(get(option, 'ResponseStrategyID')), 'ResponseStrategyName')}</b>{get(option, 'RecommendedOption') === 'Y' && <em>Recommended</em>}{get(option, 'OperationalFeasibilityID') === 'FEAS-LOW' && <i>Low feasibility</i>}</span><small>Recovery {numeric(option, 'ETARecoveryDays')}d · Cost {formatMoney(numeric(option, 'IncrementalCost'), true)} · Revenue protected {formatMoney(numeric(option, 'RevenueProtected'), true)}</small></button>)}{selected && <div className="projected"><span>Before <b>{formatMoney(numeric(exception, 'RevenueAtRisk'), true)} at risk</b></span><ArrowRight size={16}/><span>Projected <b>{formatMoney(Math.max(0, numeric(exception, 'RevenueAtRisk') - numeric(selected, 'RevenueProtected')), true)} at risk</b></span><button onClick={onApprove}>{get(selected, 'ApprovalRequired') === 'Y' ? 'Approve Action' : 'Select Action'}</button>{approved && <strong className="success"><Check size={15}/> Action saved for this session only.</strong>}</div>}</>}</section>;
}
