import { useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import data from './data/generated/executiveOverview.json';
import ibpData from './data/generated/ibpWorkbenchDemo.json';
import { ResetDemo, SharedHeader } from './SharedHeader';
import { useDemo } from './DemoContext';

type Row = Record<string, any>;
const exec: any = data, ibp: any = ibpData;
const number = (x: number) => new Intl.NumberFormat('en-US', { maximumFractionDigits: 0 }).format(x);
const dollars = (x: number) => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', notation: 'compact', maximumFractionDigits: 1 }).format(x);
const signedPercent = (value: number) => value === 0 ? '0%' : `${value > 0 ? '+' : ''}${value.toFixed(0)}%`;

export default function ExecutiveOverview() {
  const demo = useDemo(); const navigate = useNavigate(); const [channel, setChannel] = useState('ALL'); const [measure, setMeasure] = useState<'lines' | 'units'>('lines');
  const milestones = new Map(demo.milestones.map(x => [x.MilestoneID, x])); const current = ibp.planVersions.find((x: Row) => x.IsCurrent); const plan = ibp.planLines.filter((x: Row) => x.PlanVersionID === current.PlanVersionID); const latest = exec.strategicPerformance.at(-1);
  const active = demo.poLines.filter(x => { const step = Number(milestones.get(x.CurrentMilestoneID)?.StepNumber); return step >= 1 && step <= 6 && x.CancelledFlag !== 'Yes'; });
  const kpi = { stock: latest.ABSkuInStockCount / latest.ABSkuCount, coverage: plan.reduce((s: number, x: Row) => s + Math.min(x.DemandUnits, x.AvailableSupplyUnits), 0) / plan.reduce((s: number, x: Row) => s + x.DemandUnits, 0), turns: latest.Trailing12MonthCOGS / latest.AverageInventoryValue, risk: plan.reduce((s: number, x: Row) => s + Math.max(x.DemandUnits - x.AvailableSupplyUnits, 0) * (x.UnitRevenue - x.UnitCost), 0), attention: new Set(demo.poLines.filter(x => x.AtRiskFlag === 'Yes').map(x => x.POLineID)).size };
  const forecast = useMemo(() => Object.values(exec.forecastPerformance.filter((x: Row) => channel === 'ALL' || x.ChannelID === channel).reduce((out: Record<string, Row>, x: Row) => { const r = out[x.ActualMonthID] ||= { label: x.ActualMonthLabel, forecast: 0, actual: 0 }; r.forecast += x.ForecastUnits; r.actual += x.ActualUnits; return out; }, {})), [channel]) as Row[];
  const vendors = demo.vendors.map(v => { const lines = active.filter(x => x.VendorID === v.VendorID); return { v, lines, notStarted: lines.filter(x => x.VendorMilestoneStatus === 'Not Started').length, inProgress: lines.filter(x => x.VendorMilestoneStatus === 'In Progress').length, delayed: lines.filter(x => x.VendorMilestoneStatus === 'Delayed').length }; }).filter(x => x.lines.length).sort((a, b) => b.delayed - a.delayed || a.v.VendorName.localeCompare(b.v.VendorName));
  const bars = [...milestones.values()].sort((a, b) => a.StepNumber - b.StepNumber).map(m => { const lines = demo.poLines.filter(x => x.CurrentMilestoneID === m.MilestoneID); return { m, lines, value: measure === 'lines' ? lines.length : lines.reduce((s, x) => s + Number(x.Quantity), 0) }; }); const max = Math.max(1, ...bars.map(x => x.value));
  const channels = [...new Map<string, string>(exec.forecastPerformance.map((x: Row) => [x.ChannelID, x.ChannelName])).entries()];
  return <><SharedHeader title="Executive Overview" /><main className="executive-page"><section className="exec-context"><span><b>Data As Of</b>{demo.asOf}</span><span><b>Reporting period</b>February–July 2026</span><label>Channel<select value={channel} onChange={e => setChannel(e.target.value)}><option value="ALL">All channels</option>{channels.map(([id, name]) => <option key={id} value={id}>{name}</option>)}</select></label><b className="mock">Mock Data</b></section><section className="exec-kpis"><Card label="A/B SKU In-Stock Rate" value={`${(kpi.stock * 100).toFixed(1)}%`} hint="Target 90%" /><Card label="Demand Coverage" value={`${(kpi.coverage * 100).toFixed(1)}%`} hint="Fictional demo assumption" /><Card label="Inventory Turns" value={kpi.turns.toFixed(2)} hint="Target 2.0" /><Card label="Gross Margin at Risk" value={dollars(kpi.risk)} hint="Fictional demo assumption" /><Card label="PO Lines Requiring Attention" value={String(kpi.attention)} hint="AtRiskFlag = Yes" /></section><section className="exec-two"><article><h2>Forecast Bias Trend</h2><p className="exec-help" title="SME Validation Required: positive indicates over-forecast; forecast lag and accuracy method require validation.">Positive = over-forecast · zero reference shown</p><Forecast rows={forecast} /></article><article><h2>Active PO-Line Status by Vendor</h2><div className="legend"><i className="ns" />Not Started <i className="ip" />In Progress <i className="dl" />Delayed</div><VendorChart rows={vendors} onVendor={id => navigate(`/control-tower?vendor=${id}`)} /></article></section><section className="exec-milestones"><div><h2>PO Lines by Current Milestone</h2><span><button className={measure === 'lines' ? 'active' : ''} onClick={() => setMeasure('lines')}>PO Lines</button><button className={measure === 'units' ? 'active' : ''} onClick={() => setMeasure('units')}>Units</button></span></div>{bars.map(x => <button key={x.m.MilestoneID} className="mile-bar" onClick={() => navigate(`/control-tower?milestone=${x.m.MilestoneID}`)} title={`${x.lines.length} PO lines; ${number(x.lines.reduce((s, l) => s + Number(l.Quantity), 0))} units; ${number(x.lines.reduce((s, l) => s + Number(l.InventoryValue), 0))} inventory value; ${x.lines.filter(l => l.ScheduleStatus === 'Delayed').length} delayed`}><label>{x.m.StepNumber}. {x.m.MilestoneName}</label><i><b style={{ width: `${x.value / max * 100}%` }} /></i><strong>{number(x.value)}</strong></button>)}</section><section className="exec-attention"><h2>Executive Attention</h2><ul><li><button onClick={() => navigate('/ibp-workbench')}>Largest projected service gap — review IBP tradeoffs</button></li><li><button onClick={() => navigate('/control-tower')}>Highest gross-margin exposure — review Control Tower</button></li><li><button onClick={() => navigate('/control-tower')}>Most significant inbound disruption — review operational exception</button></li></ul></section><ResetDemo /></main></>;
}
function Card({ label, value, hint }: { label: string; value: string; hint: string }) { return <article><span>{label}</span><b>{value}</b><small>{hint}</small></article>; }
function Forecast({ rows }: { rows: Row[] }) { const left = 76, right = 616, top = 18, bottom = 224, ticks = [-15, -10, -5, 0, 5, 10, 15]; const y = (v: number) => bottom - (v + 15) / 30 * (bottom - top); const x = (i: number) => left + i * (right - left) / Math.max(1, rows.length - 1); const values = rows.map(r => (r.forecast - r.actual) / r.actual * 100); const points = values.map((v, i) => `${x(i)},${y(v)}`).join(' '); return <svg className="bias-chart" viewBox="0 0 640 278" role="img" aria-label="Forecast Bias Trend with a fixed minus 15 to plus 15 percent axis"><text className="axis-title" transform="rotate(-90 20 121)" x="20" y="121" textAnchor="middle">Forecast Bias (%)</text>{ticks.map(t => <g key={t}><line className={t === 0 ? 'zero' : 'grid'} x1={left} x2={right} y1={y(t)} y2={y(t)} /><line className="y-tick" x1={left - 5} x2={left} y1={y(t)} y2={y(t)} /><text className="y-label" x={left - 10} y={y(t) + 4} textAnchor="end">{signedPercent(t)}</text></g>)}<line className="y-axis" x1={left} x2={left} y1={top} y2={bottom} /><line className="x-axis" x1={left} x2={right} y1={bottom} y2={bottom} /><polyline className="trend" points={points} />{rows.map((r, i) => <g key={r.label}><circle cx={x(i)} cy={y(values[i])} r="5"><title>{`${r.label}: forecast ${number(r.forecast)}, actual ${number(r.actual)}, variance ${number(r.forecast - r.actual)}, bias ${signedPercent(values[i])}`}</title></circle><text className="x-label" x={x(i)} y={bottom + 25} textAnchor="middle">{r.label.split(' ')[0]}</text></g>)}</svg>; }
function VendorChart({ rows, onVendor }: { rows: Row[]; onVendor: (id: string) => void }) { const left = 145, right = 490, top = 25, row = 39, bottom = top + rows.length * row, scale = (v: number) => v / 15 * (right - left); return <svg className="vendor-chart" viewBox="0 0 560 270" role="img" aria-label="Active PO-Line Status by Vendor with a shared zero through 15 active PO line scale"><text className="vendor-axis-title" x={(left + right) / 2} y="263" textAnchor="middle">Active PO Lines</text>{[0, 5, 10, 15].map(t => <g key={t}><line className="vendor-grid" x1={left + scale(t)} x2={left + scale(t)} y1={top - 8} y2={bottom} /><text className="vendor-tick" x={left + scale(t)} y={bottom + 18} textAnchor="middle">{t}</text></g>)}<line className="vendor-axis" x1={left} x2={right} y1={bottom} y2={bottom} />{rows.map((r, i) => { const y = top + i * row; const title = `Not Started ${r.notStarted}, In Progress ${r.inProgress}, Delayed ${r.delayed}, Total ${r.lines.length}`; return <g className="vendor-chart-row" key={r.v.VendorID} role="button" tabIndex={0} aria-label={`${r.v.VendorName}: ${title}`} onClick={() => onVendor(r.v.VendorID)} onKeyDown={e => { if (e.key === 'Enter' || e.key === ' ') onVendor(r.v.VendorID); }}><title>{title}</title><text className="vendor-label" x={left - 10} y={y + 15} textAnchor="end">{r.v.VendorName}</text><rect className="ns" x={left} y={y} width={scale(r.notStarted)} height="20" /><rect className="ip" x={left + scale(r.notStarted)} y={y} width={scale(r.inProgress)} height="20" /><rect className="dl" x={left + scale(r.notStarted + r.inProgress)} y={y} width={scale(r.delayed)} height="20" /><text className="vendor-total" x={left + scale(r.lines.length) + 7} y={y + 15}>{r.lines.length}</text></g>; })}</svg>; }
